eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO

jwt:
  secret: supersecreto-1234567890supersecreto-1234567890
  expiration: 3600000    
