spring:
  application:
    name: gateway-service

jwt:
  secret: supersecreto-1234567890supersecreto-1234567890

cloud:
  gateway:
    discovery:
      locator:
        enabled: false
    routes:
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/security/**
        filters:
          - StripPrefix=0   # o 0 según tu backend

      - id: inventario-service
        uri: lb://INVENTARIO-SERVICE
        predicates:
          - Path=/inventario/**
        filters:
          - StripPrefix=1
          - name: JwtAuthenticationFilter

      - id: pedidos-service
        uri: lb://PEDIDOS-SERVICE
        predicates:
          - Path=/pedido/**
        filters:
          - StripPrefix=1
          - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
