spring:
  application:
    name: gateway-service

jwt:
  secret: supersecreto-1234567890supersecreto-1234567890

cloud:
  gateway:
    discovery:
      locator:
        enabled: false
    routes:
      # Ruta para AUTH (sin JWT)
      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/security/**
<<<<<<< HEAD
        #filters:
          #- StripPrefix=1
=======
        filters:
          - StripPrefix=1

      # Ruta para INVENTARIO (con JWT)
>>>>>>> 0de2129 (Arregla YAML para Spring Cloud Gateway con Config Server)
      - id: inventario-service
        uri: lb://inventario-service
        predicates:
          - Path=/inventario/**
        filters:
          - StripPrefix=1
          - name: JwtAuthenticationFilter

      # Ruta para PEDIDOS (con JWT)
      - id: pedidos-service
        uri: lb://pedidos-service
        predicates:
          - Path=/pedido/**
        filters:
          - StripPrefix=1
          - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG