server:
  port: 8083

spring:
  application:
    name: gateway-service

cloud:
  gateway:
    discovery:
      locator:
        enabled: false  # Rutas manuales
    routes:
      # Ruta para AUTH (sin JWT)
      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/security/**
        filters:
          - StripPrefix=0   # Mantiene /security en la ruta hacia el backend

      # Ruta para INVENTARIO (con JWT)
      - id: inventario-service
        uri: lb://inventario-service
        predicates:
          - Path=/inventario/**
        filters:
          - StripPrefix=1
          - name: JwtAuthenticationFilter

      # Ruta para PEDIDOS (con JWT)
      - id: pedidos-service
        uri: lb://pedidos-service
        predicates:
          - Path=/pedido/**
        filters:
          - StripPrefix=1
          - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: supersecreto-1234567890supersecreto-1234567890

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
