server:
  port: 8083

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth-service
          #lb://auth-service   # coincide con Eureka
          uri: lb://auth-service 
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

        - id: inventario-service
          uri: lb://inventario-service
          #lb://inventario-service
          predicates:
            - Path=/inventario/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

        - id: pedidos-service
          uri: lb://pedidos-service
          #lb://pedidos-service
          predicates:
            - Path=/pedido/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#jwt:
  #secret: supersecreto-1234567890supersecreto-1234567890

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
