spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: inventario-service
          uri: lb://inventario-service
          predicates:
            - Path=/inventario/**
          filters:
            - StripPrefix=1
        - id: pedido-service
          uri: lb://pedido-service
          predicates:
            - Path=/pedido/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: supersecreto-1234567890supersecreto-1234567890
